name: Deploy Secret to VM

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: infra-agent-231800
        
    - name: Setup SSH keys
      run: |
        ssh-keygen -t rsa -f ~/.ssh/google_compute_engine -N ""
        gcloud compute os-login ssh-keys add --key-file ~/.ssh/google_compute_engine.pub
        
    - name: Create key file on VM
      run: |
        gcloud compute ssh test-instance-1 --zone=us-central1-f \
        --command='echo "$KEY_CONTENT" > /home/test/sa-key.json' \
        --project=infra-agent-231800 \
        --tunnel-through-iap
      env:
        KEY_CONTENT: ${{ secrets.GCP_SA_KEY }}